---
title: "R Notebook"
output: html_notebook
---

## First, pre-install all the packages we need

```{r}
packs <- c("dplyr", "ggplot2", "lubridate", "sp", "ggmap", "gstat", "zoo", 
           "tidyr", "rsinaica")
success <- suppressWarnings(sapply(packs, require, character.only = TRUE))
if (length(names(success)[!success])) {
  install.packages(names(success)[!success])
  sapply(names(success)[!success], require, character.only = TRUE)
}
```

## Downloading the data
In order to make a map of Guadalajara, let's make sure we have data from Sinaica station:
sinaica_station_data
```{r}
parameter <- "PM10"
network <- "Guadalajara"
midpoint <- 76 # midpoint of regular air quality converted to IMECAs

## Download a single month of data for all Guadalajara stations
get_month <- function(start_date, end_date, net, parameter){
  bind_rows(
    lapply(stations_sinaica$station_id[stations_sinaica$network_name %in% net],
           sinaica_station_data, parameter, start_date, end_date, "Crude")
  )
}
## Download 2017 data, one month at a time
df <- bind_rows(
  mapply(get_month,
         seq(as.Date("2017-01-01"), as.Date("2017-12-01"), by = "month"),
         seq(as.Date("2017-02-01"), as.Date("2018-01-01"), by = "month") - 1,
         network, 
         parameter,
         SIMPLIFY = FALSE)
  )
```

Let's look at what we just downloaded
```{r}
knitr::kable(head(df))
```

## Look at the data from different neighborhoods
```{r}
df <- df  %>% 
  ungroup() %>%
  complete(station_id,
           hour = 0:23,
           date = as.character(seq(as.Date("2017-01-01"), as.Date("2017-12-31"), by = "day"))) %>%
  arrange(station_id, date, hour) %>%
  ungroup() %>%
  group_by(station_id) %>%
  mutate(roll24 = rollapply(value, 24, mean, na.rm = TRUE, partial = 12, 
                            fill = NA, align = "right")) %>%
  select(-station_name) %>%
  left_join(stations_sinaica[,c("station_id", "station_name")], by = "station_id") %>%
  mutate(datetime = with_tz(as.POSIXct(paste0(date, " ", hour, ":00"), 
                                  tz = "Etc/GMT+6"),
                       tz = "America/Mexico_City"))

ggplot(df, aes(datetime, roll24, group = station_name)) +
  geom_line(alpha = .8, size = .3) +
  ggtitle(expression(paste("24 hour average of ", PM[10], " data reported by Guadalajara stations"))) +
  xlab("date") +
  ylab(expression(paste("24 hr. average ", PM[10]," concentration in ppm"))) +
  facet_wrap(~ station_name) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=70,hjust=1))
```

# Make a grid of guadalajara
```{r}
create_grid <- function(station_vec, pixels = 1000) {
  df <- stations_sinaica[stations_sinaica$station_id %in% station_vec,]
  geog <- df[,c("lat", "lon")]
  coordinates(geog) <- ~lon+lat
  proj4string(geog) <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
  ## Add a margin surrounding the stations
  geog@bbox <- bbox(geog) + c(-0.05, -0.05, 0.05, 0.05)
  geog.grd <- makegrid(geog, n = pixels)
  
  grd.pts <- SpatialPixels(SpatialPoints(geog.grd))
  as(grd.pts, "SpatialGrid")
}

reporting_stations <- unique(df$station_id)
# 50x50 grid covering Mexico City
grid <- create_grid(reporting_stations, 15000)

plot(grid, main = "Grid covering Guadalajara and Locations of\nPollution Measuring Stations (red)",
     col = "#666666", lwd = .2)
# Plot the locations of the stations
geog <- stations_sinaica[stations_sinaica$station_id %in% reporting_stations, 
                         c("lat", "lon", "station_code")]
coordinates(geog) <- ~lon+lat
points(geog, pch = 22, col = "lightgray", bg = "tomato1", cex = 1.2)
text(geog$lon, geog$lat, geog$station_code, pos = 1)

```


## Making the map

#### Step 1
```{r}
heatmap <- function(df, grid){
  if(nrow(df) == 0){
    return(data.frame(var1.pred = NA, var1.var = NA, lon = NA, lat = NA))
  }
  
  df <- left_join(df, stations_sinaica, by = "station_id")
  df <- df[!is.na(df$value),]
  df <- df[,c("lat", "lon", "value")]
  coordinates(df) <- ~lon+lat
  # For radiation pollution the exponent should be 2
  # See http://www.sciencedirect.com/science/article/pii/S009830041200372X
  df.idw <- idw(value ~ 1, df, grid, idp = 2, debug.level = 0)
  
  idw = as.data.frame(df.idw)
  names(idw) <- c("var1.pred", "var1.var", "lon", "lat")

  idw
}
```

#### Step 2
```{r}
df <- df %>%
  group_by(station_id, date) %>%
  summarise(maxroll24 = max(roll24, na.rm = TRUE)) %>% 
  mutate(maxroll24 = if_else(!is.finite(maxroll24), NA_real_, maxroll24)) %>%
  group_by(station_id) %>%
  summarise(value = mean(maxroll24, na.rm = TRUE))
idw_tiles <- heatmap(df, grid)

```

#### Step 3
```{r}
qmplot(x1, x2, data = data.frame(grid), geom = "blank", 
       maptype = "toner-lite", source = "stamen", zoom = 10)  +
  geom_tile(data = idw_tiles, aes(x = lon, y = lat, fill = var1.pred), 
            alpha = .8) + 
  ## set midpoint at 76 cause that's bad air quality according to
  ## http://www.aire.cdmx.gob.mx/default.php?opc=%27ZaBhnmI=&dc=%27aQ==
  scale_fill_gradient2(expression(paste(mu,"g/", m^3)), 
                       low = "#abd9e9",
                       mid = "#ffffbf",
                       high = "#f46d43",
                       midpoint = midpoint) + # midpoint of regular air quality converted from IMECAs
  geom_point(data = stations_sinaica[stations_sinaica$station_id %in% reporting_stations, ],
             aes(lon, lat), shape = 22, size = 2.6) +
  ggtitle(expression(paste("Average of ", PM[10], 
                           " daily maximums in Guadalajara during 2017")))
```

